[build]
  command = "npm run build"
  publish = "Passliss Web/passliss/.next"
  base = "Passliss Web/passliss"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NETLIFY_BUILD_IMAGE = "xenial"

[[plugins]]
  package = "@netlify/plugin-nextjs"